### ISSUE TITLE
Add a CI/CD file for Github.

### ISSUE THREAD

**Issue by FlorianWilhelm** [FlorianWilhelm/the-hatchlor#1]
### Description

It would be nice to have an option that asks if a folder with a github setup should be created.

**Comment by Aviksaikat** [comment]
I have done a similar thing with my hatch template you can check it out [here](https://github.com/Aviksaikat/cookiecutter-hatch-pypackage/tree/main/%7B%7Bcookiecutter.dist_name%7D%7D/.github). Thre are some basic workflows here

**Comment by FlorianWilhelm** [comment]
@Aviksaikat, awesome 🤩  Your template is really similar. I wonder if we could just merge them?

**Comment by Aviksaikat** [comment]
Sure!! I'll update the workflows. And working on a bate minimum template for general purpose projects

**Comment by Aviksaikat** [comment]
Workflows updated do you want me to open a PR ?

**Comment by Aviksaikat** [comment]
I'm glad that you liked the template. We learn something new every day :smiley: . The workflows are updated to hatch now. I'll open a PR soon.

**Comment by FlorianWilhelm** [comment]
Thank you @Aviksaikat.
