### ISSUE TITLE
Support for codeblocks

### ISSUE THREAD

**Issue by dornech** [FlorianWilhelm/the-hatchlor#11]
If I am not wrong, hatchlor currently does not support codeblocks.
Might be an option to add this to the pyproject.toml-template ?

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

**Comment by FlorianWilhelm** [comment]
Hi @dornech, ah, maybe I forgot this! Thank you. Could you provide a PR for it?

**Comment by dornech** [comment]
As mentioned elsewhere ... I am rigth now just starting to learn how to work with GitHub and publishing packages ... so I am, not sure if I would know how to do it ...

**Comment by FlorianWilhelm** [comment]
I just checked it @dornech. Those options are included in `mkdocs.yml` as they are mkdocs configuration options, so not in `pyproject.toml`.
