### ISSUE TITLE
Python minimum version for generating documentation

### ISSUE THREAD

**Issue by dornech** [FlorianWilhelm/the-hatchlor#15]
The documentation build Github Action uses the defined Python minimum version but the defined dependencies require Python 3.10 at least. If one wants to publish code which still runs with Python 3 below 3.10, this causes an error in the documentation build.

I do not think the documentation build Pytohn version depends on the package target verison. so this could be changed in the hatchlor template.

**Comment by FlorianWilhelm** [comment]
Hi @dornech and thanks for reporting. Just to be sure that I understand you correctly. Right now building the documentation and the minimum required Python version for the package are set consistently by using the variable `target_python_version`. The default is set to 3.10 but you can of course choose a lower version. 

You are suggesting to split this up into two variables as the package itself could require a higher Python version than when building the docs. Is this correct? What is your exact use-case? Do you have an example where you want the Python version in your docs lower than in the minimum requirement of your package? 

Technically, you are right but this is quite an edge case and introducing one more parameter configuration option increases the complexity more and might confuse users.

**Comment by dornech** [comment]
Yes. Or probably setting Python Version for the document building fixed to 3.10 or above. As the GitHub Action does this on the server side, this causes no problem, does it?

**Comment by FlorianWilhelm** [comment]
Okay, so you had the problem that you choose 3.8 as target version and linkchecker complained that it needed 3.10? Could you please provide more information and maybe the log output?

**Comment by dornech** [comment]
![grafik](https://github.com/user-attachments/assets/22b259fb-69fc-4ee7-89d4-81b60ad8f4ad)

**Comment by dornech** [comment]
Linkchecker requires 3.9 at minimum. 
https://pypi.org/project/LinkChecker/

**Comment by FlorianWilhelm** [comment]
Thanks @dornech. The problem I see is that Python 3.8 is already [end-of-life](https://devguide.python.org/versions/) and should no longer be supported anyway. What do you think if we just drop it completed from the hatchlor cookiecutter config? That would also solve this problem as the minimum version is then 3.9 and linkchecker works?

**Comment by dornech** [comment]
Well, of course this is an option. I just wonder for support on older version - Hatch itself claims to support 3.8. and even I was not part of the Python community when switching from 2 to 3 that time, I remember there was a pretty long time not all user having switched. But probably the culture has changed and for my purpose this is fine.

**Comment by dornech** [comment]
BTW: funny side effect. Even setting python-version to 3.10 in documentation.yaml, in the log an error is generated that 3.8 is used as set in pyproject.toml.
This seems to be related to the following issue:
https://github.com/pypa/hatch/issues/1623

**Comment by FlorianWilhelm** [comment]
Thanks @dornech, I removed Python 3.8 and added Python 3.13. With this changes it should work. Commit is 302e0ec16e95096d539ac6330f984cab086c5558.
