### ISSUE TITLE
Error pyproject.toml testmatrix

### ISSUE THREAD

**Issue by dornech** [FlorianWilhelm/the-hatchlor#18]
Testmatrix is defined as follows:
![grafik](https://github.com/user-attachments/assets/a6528c46-75d4-4908-b5e7-e2e37d825b01)

I think the table name should read 
[[tool.hatch.envs.test.matrix]]
?

Or is it intended to have test as envrionment and py-test as separate test matrix and (implicit) envrionment?
However, if I do 
hatch run py-test:cov 
which then should execute test:cov for all matrix entries, I get an error that cov is not defined.

**Comment by FlorianWilhelm** [comment]
Thanks @dornech, this is fixed in 9cfeb94.
