### ISSUE TITLE
Prompting project informations runs into an error

### ISSUE THREAD

**Issue by tomasito12** [FlorianWilhelm/the-hatchlor#6]
* Date you used The Hatchlor: April 26th, 2024
* Cookiecutter version used, if any: 2.6.0
* Python version, if any: 3.10
* Operating System: Mac OS

### Description

Hi @FlorianWilhelm , I saw your great talk at Pycon, and I am very keen to try out the-hatchlor. However, trying to answer the prompts after starting cookiecutter leads into an error that I am unable to resolve. 
For every prompt, I set the defaul argument. Then I received the following prompt: "_ _prompts_ _ [default] ". This seems to be a generic placeholder that should not pop up. When I pressed enter to chose the default, I got the error message "Error: Unable to decode to JSON". I expected to receive the next prompt instead. 

### What I Did
![Bildschirmfoto 2024-04-26 um 08 44 59](https://github.com/FlorianWilhelm/the-hatchlor/assets/60884010/1dcc6a83-47b8-4602-b7ba-a66c43cfd351)

```
cookiecutter https://github.com/florianwilhelm/the-hatchlor.git
You've downloaded /Users/thomasplischke/.cookiecutters/the-hatchlor before. Is it okay to delete and re-download it? [yes]: y
full_name [Florian Wilhelm]: 
email [email@example.com]: 
project_name [Python hatch project]: 
project_slug [python-hatch-project]: 
pkg_name [python_hatch_project]: 
project_short_description [Python project featuring the modern and extensible Python project manager hatch.]: 
Select open_source_license:
1 - MIT
2 - BSD-3-Clause
3 - ISC
4 - Apache-2.0
5 - GPL-3.0-only
6 - proprietary
Choose from 1, 2, 3, 4, 5, 6 [1]: 
Select target_python_version:
1 - 3.10
2 - 3.8
3 - 3.9
4 - 3.11
5 - 3.12
Choose from 1, 2, 3, 4, 5 [1]: 
github_username [FlorianWilhelm]: 
project_repo [https://github.com/FlorianWilhelm/python-hatch-project]: 
pypi_username [FlorianWilhelm]: 
lock_file_support [False]: 
__prompts__ [default]: 
Error: Unable to decode to JSON.
```

**Comment by FlorianWilhelm** [comment]
Hi @tomasito12 , thank you!

I just ran it on my Macbook with Cookiecutter 2.6 and it worked, also the Github Actions based unit tests. The `__prompts__` JSON-value is defined in [cookiecutter documentation](https://cookiecutter.readthedocs.io/en/stable/advanced/human_readable_prompts.html). It's hard to understand what's happening here. Could you re-create your environment?

**Comment by tomasito12** [comment]
Hi @FlorianWilhelm ,
sorry, I should have come up with the idea of resetting the environment myself. With a complete new environment, it actually worked without problems! Interestingly, I changed back to my old environment in order to replicate the faulty behavior, but then, rather magically, worked with the old environment, as well. 
So, thank you a lot for helping me out and providing this nice little tool!
